DMTF/Redfish-Service-Validator

RedfishServiceValidator.py

validateEntity() is called for items that are an EntityType. It assumed the required @odata.id property was present and would get an exception if it wasn't. Added explicit check that @odata.id is present. And if not issue an appropriate error message.
The error message looks like this:
ERROR - Power.v1_0_0.PowerSupply:Redundancy: EntityType resource does not contain required @odata.id property
Fixes #105 
@jautor - fix for #105 is in this PR.

Add check and error message for missing @odata.id in validateEntity()

---

traverseService.py

Added check that the RedfishExtensions namespace in $metadata has the expected Alias value of 'Redfish'. If not, it generates an error message like this:
"ERROR - In the resource $metadata, the RedfishExtensions.v1_0_0 namespace must have an alias of 'Redfish'. The alias is 'RedfishExtensions'. This may cause properties of the form [PropertyName]@Redfish.TermName to be unrecognized."
Initially, I tried to make it so that this error is only generated once. Unfortunately, I ran into issues getting that to work based on where the getReferenceDetails() function is called from. So, for now, the message will appear once in each resource section of the HTML report. I'll revisit this in future. But I wanted to go ahead and push this version since it is working and I think will be helpful.
Fixes …

Add check for proper RedfishExtensions alias in $metadata

---

RedfishServiceValidator.py
traverseService.py

Fixes accidental introduction of a second code loop in move-config
Fix #99, given that /redfish/v1/$metadata accurately resolves as a valid XML file

Removed accidental repeat from move-config PR, fixed $metadata bug

---

traverseService.py

Added special handling for MessageRegistryFile schema resources referenced by the Location -> Uri property.
Fixes #94 
Screenshot showing the beginning of one of the subject resources in the validation report:

add logic to handle Registry location uri resources

---

RedfishServiceValidator.py
traverseService.py

Addresses the first item mentioned in #77.
- For properties with the Redfish.DynamicPropertyPatterns annotation, validates that the keys match the specified pattern and that the values are of the specified type.
- Also fixes a bug in the tool where a NoneType is dereferenced.
- And corrects an issue where the wrong logger instance is used to log an error.
There are some additional issues described in #77 that I'm still working on, so will keep that issue open.
Screenshot showing the beginning of the Bios resource validation report. Note that a couple of errors were introduced in the payload:
And a screenshot showing the end of the Bios resource validation report. Note the errors for the 2 validation failures:

Validate Redfish.DynamicPropertyPatterns for Bios Attributes

---

RedfishServiceValidator.py

Added encoding='utf8' to open() of html report file to fix the reported UnicodeEncodeError.
Fixes #116

Add encoding=utf8 to html file open to fix UnicodeEncodeError

---

RedfishServiceValidator.py
traverseService.py

Validate Bios attributes against attribute registry:
- Ensure Registries are loaded early so the contents will be available for validation of other resources (e.g. Bios)
- Load any attribute registries found into dictionaries that can be retrieved later
- When validating attribute properties in Bios, validate against the type specified in the attribute registry
Fixes #77 
A couple of screenshots to show how validation failures from the attribute registry checks will look:

Validate Bios attributes against attribute registry

---

RedfishServiceValidator.py

Corrected the Nullable property validation logic. Behavior now is:
- If an entry in a collection is null and the collection property is Nullable, validation passes
- If an entry in a collection is null and the collection property is NOT Nullable, validation fails
- If the value of the collection itself is null (rather than an entry in the collection), validation fails
- For primitive (non-collection) properties, the logic is consistent with the first 2 bullets above
Fixes #117 
Here are a couple of screenshots showing the original behavior where the tool incorrectly flagged a null collection value as invalid (even though the property was Nullable):
And here is a screenshot showing the same validation after the fix. Validation now passes:
Also, if an entry is null and the property is NOT …

Fix Nullable property validation logic

---

README.md
RedfishServiceValidator.py
config.ini
traverseService.py

Add sampling support for large collections:
- added `--sample N` command-line option and `Sample = N` config.ini property to specify sample size
- the default is to validate all collection members
- if the sample size is greater than or equal to the collection size, all members are validated (no sampling)
- a sample size of zero (or less than zero) means to validate all members (no sampling)
- if both link limit and sample size apply to a given collection, link limit takes precedence
Fixes #100 
Here is some debug output showing a mix of link limit and sampling being performed (Sample = 5, LinkLimit = {LogEntry:20}):
```
DEBUG - Limiting "SoftwareInventory" to sample of 5 links
DEBUG - Limiting "Voltage" to sample of 5 links
DEBUG - Limiting "IPv6Address" to sample of 5 links
DEBUG - …
```

Add support for sampling random members from large collections

---

RedfishServiceValidator.py

Original logic in validation of DynamicPropertyPatterns and attribute registries did not allow null values. These primitive types can be null. Updated to allow null values.
Fixes #130

Allow null values for primitives in DynamicPropertyPatterns and attribute registries

---

RedfishServiceValidator.py

Includes these improvements for #137:
- In the resource report tables, improves readability for fields in the Name, Value, Types, Exists and Result columns
- In the header section, improved readability and formatting
Work still remaining for #137:
- If property, enum, etc. not found in schema, do a case-insensitive check to report case errors
- Make Configuration section human readable and collapse the less-important settings
- Make Final Counts section a Test Summary section and make it more human readable
- Continue making enhancements described in #137 under "Header improvements", item (7)
- All items described in #137 under "Error case enhancements"
**Header BEFORE:**
**Header AFTER:**
**ServiceRoot BEFORE:**
**ServiceRoot AFTER:**
**Systems BEFORE:**
**Systems AFTER:**

HTML report improvements for issue 137, part 1

---

README.md
RedfishServiceValidator.py
traverseService.py

Per discussion in issue #76, updated code to only use proxies for URLs external to the service being tested.
I tested the proxy feature using the Charles proxy and confirmed it is working as expected.
Also fixed an unrelated bug with the handling of SingleFile payload mode that I saw during testing.
Fixes #76

Update proxies to only apply to URLs external to the service

---

RedfishServiceValidator.py

Updates included in this PR:
- Improved error message in validateEntity() for schema version or namespace not found per the suggestion in issue #149. Also made the debug messages in this function more usable.
- Improved error message for undefined property (issue #159).
Fixes #149
Fixed #159

Improve error messages for schema not found and property not defined

---

RedfishServiceValidator.py

When schema errors are logged via traverseService.py, the functions that module do not have access to the result counters for the resource being processed. So those errors show up in the report at the end of the resource section, but they are not accounted for in the summary counts in the header of the resource section.
This PR includes a tactical fix during report generation that checks for this condition and adds a failure counter to the resource summary so that it will be highlighted in red. This makes it obvious there is a problem with the resource even without expanding the details.
Fixes #151 
Fixes #154

Ensure resource header shows failure if any errors logged for resource

---

RedfishServiceValidator.py

Fixes #156 , but debates whether or not there is a better option

Added option to enable debug logging to txt, off by default

---

RedfishServiceValidator.py
traverseService.py

Commit rewrites certain variable names in getPropertyDetails, and corrects the issue of ComplexTypes not gathering all their properties.
Fixes #160 
Commit adds check for deprecated tag as well.

Fix to complex types not assuming highest type, +deprecate tag check

---

RedfishServiceValidator.py
traverseService.py

Report improvements:
- formatted array member properties to use standard notation (`RegistryEntries.Attributes[279].Value[4].ValueName` vs. `RegistryEntries.Attributes.Value.ValueName#4#279`)
- property names in error messages consistent with how they are shown in the resource report tables
- fixed formatting of error messages to remove extraneous text before the property name that had the error
Fixes #150 
Before:
After:

Improve display of array member properties in report

---

RedfishServiceValidator.py
traverseService.py

Adds collection sample notation to the resource URI report headers.
Before:
After:
Fixes #152

Add collection sample notation to the resource uri report headers

---

traverseService.py

If there was a Location entry in a MessageRegistryFile resource that did not have a Uri property, it would try to validate one anyway, resulting in a mangled URI. Fixed by doing better validation of the property. 
Fixes #174

Better input validation for MessageRegistryFile Location Uri

---

RedfishServiceValidator.py
traverseService.py

Made the following updates:
- If an `@Redfish.ActionInfo` payload annotation is present in an Actions block, add the referenced URI to the set of resources to be validated. So these resources now get validated just like other resources.
- Validate that the only allowed properties within the actions property are `target`, `@Redfish.ActionInfo`, and `*@Redfish.AllowableValues`.
- If the `target` property is missing, an error is emitted (per recent spec clarification)
Fixes #182

Enhance validation of Actions block

---

RedfishServiceValidator.py
metadata.py
traverseService.py

Added new $metadata validation section to HTML report. Also added fix for issue described in #195.
Fixes #185 
Fixes #195 
New $metadata report section (appears at beginning of report) shows $metadata validation errors:
After cleaning up errors:
Regarding the fix for issue #195: If, for example, the AccountService schema reference is missing from the $metadata, you would previously get a result like this:
After the fix, the missing reference is reported, but the correct schema uri is assumed, the schema is fetched and the validation proceeds:

Add new $metadata validation section to HTML report

---

rfSession.py

Fixed the code to handle relative or absolute URL for the session (used by killSession() to delete the current session).
Fixes #199

Correct bug with the server url used to delete session

---

RedfishServiceValidator.py
rfSession.py
traverseService.py

Enhanced error handling for authentication failures due to invalid creds.
If we get an error while creating the session for session auth, or a 401 http status for a service uri when using basic or token auth, an appropriate error is logged to STDOUT and to the *.txt log file. No HTML report is generated if these errors are encountered.
The error message for the Session auth case will look like this:
> Error creating session. Status code "400 Bad Request". Check supplied username and password.
The error message for the Basic auth case will look like this:
> Error accessing URI /redfish/v1/Systems/System.Embedded.1/Processors. Status code "401 Unauthorized". Check username and password supplied for "Basic" authentication.
And the error message for the Token auth case will look like this:
> …

Enhanced authentication error handling for basic and session auth

---

RedfishServiceValidator.py

For properties that are odata Collection types, use the term "array" in the report rather than "collection".
Before:
`Collection, size: 3`
`collection of: IPv4Address`
After:
`Array (size: 3)`
`array of: IPv4Address`
Fixes #192

Avoid "collection" odata term in report; use "array" instead

---

metadata.py

From the scenario encountered in issue #206:
The $metadata had a schema reference like this:
```
<edmx:Reference Uri="/redfish/v1/Schemas/VLanNetworkInterfaceCollection_v1.xml">
<edmx:Include Namespace="VLanNetworkInterface"/>
</edmx:Reference>
```
This was likely due to a copy-and-paste error and can be hard to spot just from visual inspection. This PR adds additional checking to the $metadata validation that verifies that all namespaces included from a schema URI are actually in that schema. For the example above, this is the error shown in the $metadata report section:
Fixes #206

Validate includes in metadata are defined in the referenced schema

---

traverseService.py

Old:
> ERROR - type doesn't exist? Resource.Location
> ERROR - Something went wrong
> Traceback (most recent call last):
>  File "/Users/bdodd/Development/git/Redfish-Service-Validator/traverseService.py", line 673, in __init__
soup, refs, propOwner, propChild, tagType, topVersion)
> File "/Users/bdodd/Development/git/Redfish-Service-Validator/traverseService.py", line 992, in getPropertyDetails
"getPropertyDetails: problem grabbing type: " + propertyFullType)
> Exception: getPropertyDetails: problem grabbing type: Resource.Location
> ERROR - #Chassis.v1_2_0.Chassis:Location :  Could not get details on this property
New:
> ERROR - Type Location not found under namespace Resource in schema http://redfish.dmtf.org/schemas/v1/Resource.xml
Old:
> ERROR - Got XML, but expected schema doesn't …

Avoid exception and better errors in getPropertyDetails and getTypeDetails

---

README.md
RedfishServiceValidator.py
RedfishServiceValidatorGui.py
cache/README.md
simpletypes.py
tests/simpleeval.py
tohtml.py
traverseService.py

Repartitioned pieces of code for easier unittesting in the future.
Implemented partial log changes similar to issue #212, only reporting errors and warns.  Now has the option to display extensive testing data with --verbose_checks.
Split warns and errors in HTML log to differentiate the messages.
Examples:
```
% python3 RedfishServiceValidator.py --ip 127.0.0.1:8000 --nossl
ConfigURI: 127.0.0.1:8000
System Info: No desc
authtype: Basic,  cachefilepath: ./cache,  cachemode: Off,  certificatebundle: None,  certificatecheck: False,  config: None,  
configuri: http://127.0.0.1:8000,  debug_logging: 20,  httpproxy: None,  httpsproxy: None,  linklimit: {'LogEntry': 20},  localonlymode: False,  
logpath: ./logs,  metadatafilepath: ./SchemaFiles/metadata,  sample: 0,  schemasuffix: _v1.xml, …
```

Cleaner log output, repartitioning code for tests, split warn/error

---

README.md
RedfishServiceValidator.py
config.ini
traverseService.py

Disables auth credentials if in a situation where forceauth is not specified but https/ssl is not being used. 
If Redfish.Copyright is checked, then throw an error and specify why.

Add in ForceAuth option, Redfish.Copyright check

---

README.md
RedfishServiceValidator.py
commonRedfish.py
config.ini
metadata.py
traverseService.py

Adds Complex Dynamic Checking necessary for OEM items, while previously only did Basic types.  (Has an issue with systems with incomplete $metadata, and message spam with MessageRegistries, but seemed to only happen in one given system.)
Don't skip over OEM items and allocate links properly while checking the items.  Add option to enable oemchecks as needed.  (This is done in Validator, but should be handled when constructing our Resource)
Additionally adds some generators for the internal objects
Sans OemCheck:
With OemCheck:
Before ComplexCheck:
After ComplexCheck:

Adds Complex Dynamic checking and OEM Item/Link checking, reworks

---

RedfishServiceValidator.py
traverseService.py

I reran the service validator against the mockups of the systems that showed the tracebacks in the HTML reports. And most of the issues had already been resolved by the fixes @tomasg2012 made a couple of weeks ago (thanks, Tomas).
There were still some traceback errors generated in the HTML reports in places where an exception was caught and an error with traceback was generated via `logger.exception("Something went wrong")`.
I changed those occurrences to only log the traceback in the debug logging and verified that an appropriate error was logged in the HTML report.
Fixes #257

Removed exception tracebacks from error messages

---

traverseService.py

Updates:
- If exceptions occur during the acquiring and decoding of a resource response, only log the traceback at DEBUG level (do not include traceback in HTML report)
- Enhanced the error messages to show the type of exception raised and the exception message.
- In the exception case, if a response payload was received, its contents will be logged at DEBUG level.
fixes #277

Send traceback to debug logging only, not to HTML report

---

README.md
RedfishServiceValidator.py
commonRedfish.py
metadata.py
rfSchema.py
simpletypes.py
tests/complexeval.py
tests/schema.py
traverseService.py

Added automatic file cacheing of XMLs pulled from DMTF/Service
Added proper message for navigating links to Entities with incorrect types
Verify an odata_id with a fragment properly resolves to itself, via its parent
Properly start from '/redfish/v1/' instead of '/redfish/v1'
Add missing license comments
Fixed missing logger in commonRedfish
Updated current schema_pack zip to latest 2018.2
Removed stripping from Redfish.Uris checking (compareUri)
Fixed missing default option for usessl
Print verbosely what options overwritten for RedfishVersion protocol
Minor code reformatting (pep8, unused lines)

Fixes to minor bugs, missing features

---

RedfishServiceValidator.py

Updated code to only emit the empty string warning when the property is read-only.
Fixes #285

Only emit empty string warning for read-only properties

---

metadata.py

Update schema zip URL to point to 2019.1 bundle

---

RedfishServiceValidator.py

Per comment by @jautor in #317, updated error to be more helpful.
Before:
```
ERROR - MetricReport: Could not get resource for Entity check
```
After:
```
ERROR - MetricReport: GET of resource at URI /redfish/v1/TelemetryService/MetricReportsCPUUtilCustom1/ returned HTTP 404. Check URI.
```
Fixes #317

Improve error message for HTTP GET uri failures

---

RedfishServiceValidator.py

Per issue #320, eliminate WARNING for @odata.etag properties.
Fixes #320

Remove warning for @odata.etag properties

---

RedfishServiceValidator.py

Updated validation logic for Actions to allow the (relatively) new @Redfish.OperationApplyTimeSupport annotation.
Fixes #340

Allow OperationApplyTimeSupport in Actions

---

RedfishServiceValidator.py
commonRedfish.py
traverseService.py

Log statements pertaining to checking if a fragment is valid have been improved.
Fixes #341 
Early return statement gives bogus data for the link generating function.
Fixes #339

Changes to messages related to JSON fragments, fix for early return

---

commonRedfish.py
rfSchema.py

Allows for digits to be more than one digit in a version number.  Properly splits and compares each digit for version formatted with `v1_x_x` format.
Fixes #346

Added fix to double digit version numbers

---

commonRedfish.py
metadata.py
rfSchema.py

Correctly addresses versions above a single digit size.
Fixes #349

Updates to support 2019.2 versioning and schemapack

---

commonRedfish.py
rfSchema.py

previous:
```
*** /redfish/v1/Chassis                                                                                                                                                   
Type (#ChassisCollection.ChassisCollection), GET SUCCESS (time: 0.003215)                                                                                        
Verifying property that does not belong to this version: Resource.v1_0_0.ResourceCollection:Description                                                                   
Verifying property that does not belong to this version: Resource.v1_0_0.ResourceCollection:Name                                                                          
FAIL... 
```
new:
```
*** /redfish/v1/Chassis                      
Type …
```

Explicit checks to typechain for property version validation

---

commonValidator.py

Without this fix, Navigation Properties like "EntityLink" in Endpoint would fail since the tool is explicitly looking for a resource of type "Resource.Resource" instead of allowing for any type of resource.

Added missing allowance for Resource.Resource or generic links

---

README.md

While the variable in the code is called "LocalOnly", the option in
the config file is called "LocalOnlyMode". Adapt the README to reflect
this.

[Trivial] Correct option name LocalOnly to LocalOnlyMode

---

traverseService.py

Fixed 'is' and 'is not' comparisions that are not allowed in Python3.8+

---

traverseService.py

Creating a Session will allow us to persist certain connection parameters across requests thereby making them faster.
There is a detailed analysis in here: https://stackoverflow.com/questions/32986228/difference-between-using-requests-get-and-requests-session-get
The following sample snapshot shows amount of time saved by this addition,

Add requests.Session to optimize HTTP connection time

---

schema_pack.py

Fix #422 
2021.2 was released yesterday, Sept 22nd.
Move the schemapack default (i.e. if --source not given) to 2021.2
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>

Move schemapack default to 2021.2

---

README.md
RedfishServiceValidator.py
RedfishServiceValidatorGui.py
common/catalog.py
common/config.py
common/helper.py
common/schema.py
common/traverse.py
tests/test_catalog.py
tests/testdata/schemas/Example_v1.xml
validateRedfish.py
validateResource.py

The tool can now check URIs on any service at and above version 1.6.0,
testing all @odata.id possible on each Resource.
Now tests headers to check if Capabilities is properly applied to the
Allow header.
fix: MinVersion is now lessthan or equal
fix: Fix modified results using success rather than result
tweak: Changes to support checking headers...
...
Changed Error to Warn on PATCH/PUT header msg
Renamed variables several variables, made URI checking less strict
Loosened URI pattern regex, Pound sign check for fragments
...
tweak/fix: Simplified fulltype variable, proper check for incorrect non-dictionary RedfishObject values
fix: Fixed DynamicProperties being incorrectly pulled from schema

Add URI checking and Capabilities checking, bug tweaks, Registry files (squashed)

---

validateRedfish.py

E.g. for EthernetInterface.v1_6_4.EthernetInterface IPv4Addresses lists,
the list index "[<index>]" was missing in HTML/CSV output. For lists of
size 1 the index was missing completely, otherwise "#<index>" was appended,
e.g. "IPv4Addresses.SubnetMask#1".
With this change, regardless of the size of the list, "[<index>]" will be
used in the same way as for "Members" etc, e.g.
"IPv4Addresses[1].SubnetMask".
Signed-off-by: Andreas Heynig <andreas.heynig@mk-logic.de>

Fix output for lists of 'ComplexType'

---

common/catalog.py
common/config.py

Fix #444 
Partially addresses some of the `--nooemcheck` usage for setting up the configuration file. More work needed in this for skipping links found inside `Oem`.

Corrected scanning of object properties within OEM objects

---

common/traverse.py

Fix #452 
From testing, this change is not needed if the python-redfish-library is version 3.1.0 or higher, but this has no negative consequences if the latest is used.

Specify that any content encoding is allowed

---

common/catalog.py

Enhanced '@odata.id' inspection to not crash when the value is an empty string

---

validateResource.py

Added check to ensure a reference object is an object prior to attempting to extract the link information

---

common/catalog.py
common/helper.py
common/schema.py
common/traverse.py
schema_pack.py
validateRedfish.py
validateResource.py

It's an enhancement to use `logger.warning` instead of `logger.warn` (which is deprecated)

Unify to use logger.warning

---

common/catalog.py
common/schema.py

This is a cleaner version of #468 that was inadvertently closed (and as a contributor I don't think I can reopen).
This branch makes beautifulsoup ignore the namespace on schemas, and pull by only the tag name.

Remove beautifulsoup XML namespace lookups

---

README.md

Added a critical missing step, the actual command line to run.
Fixed typo of backslash vs forward slash, and reworded text slightly.
Signed-off-by: Josh Lehan <krellan@google.com>

README: Added example command line

---

RedfishServiceValidator.py
validateResource.py

Currently all referenceable member checks report a warning "WARNING - No parent found with which to test @odata.id of ReferenceableMember". Root caused the issue to be improper usage of the parent reference when scanning the next level of resources.
Made additional changes to allow for arguments other tools use for consistency in the CLI usage. For example, most tools use `rhost` for providing the service address, so a user can use `rhost` in favor of `ip` if desired.

Corrected parent reference to allow for '@odata.id' testing on referenceable members

---

common/helper.py

Program incorrectly flagged @odata items with property names prefixed, i.e `Members@odata.count`.

Fix to odata count not checking correctly

---

RedfishServiceValidator.py
RedfishServiceValidatorGui.py

On Linux systems, being able to execute the scripts directly both
informs users which python should be used, and allows less typing.

Make service validator executable directly

---

redfish_service_validator/RedfishServiceValidator.py

Because of the conditional imports, when doing the name change from
common to redfish_service_validator, one import got missed.  This causes
a bug where, if the schema pack directory is empty, redfish service
validator fails with an ImportError.
This commit fixes the import.
Tested:
Deleting the SchemaPack and running the service validator no longer
fails.
Signed-off-by: Ed Tanous <edtanous@google.com>

Fix bug in schema pack download

---

redfish_service_validator/RedfishServiceValidator.py
redfish_service_validator/config.py

Conditional imports, while useful in a minor way to save ram, lead to
situations where dependencies are harder to trace, and migrations are
harder to execute.
Python pep8 also says:
"Imports are always put at the top of the file, just after any module
comments and docstrings, and before module globals and constants."
https://peps.python.org/pep-0008/#imports
We should follow that advice.  This commit moves all imports to be at
the top of the file.
Signed-off-by: Ed Tanous <edtanous@google.com>

Remove conditional imports

---

redfish_service_validator/catalog.py

Fix #505 
May also address #495, but can't confirm without debug data

Corrected link traversal logic when objects or arrays of objects are 'null'

---

RedfishServiceValidator.py
redfish_service_validator/RedfishServiceValidatorGui.py
redfish_service_validator/validateRedfish.py
redfish_service_validator/validateResource.py
tests/test_catalog.py

Returns status code if running from console
Corrected GUI not importing right library
Moved 'FAIL' message to 'Additional' if additional property is not defined in Complex object
Report @odata.id is missing from payload
Small test error fixed
Fix #515 
Fix #514

Generate error on missing @odata.id, misc fixes

---

redfish_service_validator/helper.py

Fix #530 
Only allowing this for the ServiceRoot resource since it's an oddly defined one from 1.0 where it has two well-known URIs (/redfish/v1/ and /redfish/v1), and services can implement this in a manner where they serve the same static file.

Added exception in '@odata.id' validation to allow for trailing slash discrepancy with the ServiceRoot resource

---

redfish_service_validator/validateRedfish.py

Corrected logic to ignore null checks for the HttpHeaders property for EventDestination resources

---

redfish_service_validator/catalog.py
redfish_service_validator/validateResource.py

Removes portion of code that removes URI checking on specific instances of "inAnnotation" variable being set to True, which occurs when URIs exist in particular contexts (this would toggle `ignore_uri_checks`).  This should not ignore URIChecks, and correctly set variables for standard URIs.
However, the reason for this code to exist is not explained, nor is it practical as it applies on a first-come basis, which labels some URIs as based on Annotations when they are standard URIs.
Also adds a line which makes StrictURI flag true outside of the UriCheck block, which only affects the program if `ignore_uri_checks` was True.
Fixes #538

Remove uri_check toggling for inAnnotation variable

---

redfish_service_validator/catalog.py

Fix #547 
Currently only reporting a warning instead of an error; may need to discuss this a bit since using undefined annotation is illegal, but could be detrimental for cases like this.

Added handling of cases where a payload annotation's definition cannot be located in schema files

---

redfish_service_validator/validateResource.py

Encountered a conformance issue where `@odata.id` for a handful of properties was not a string, but instead was an array of strings. This would cause the tool to crash. Change added to log an error and move on with testing.

Added check to ensure the '@odata.id' value is a string before trying to follow the link

---

redfish_service_validator/validateRedfish.py

Would like to see if others agree with this, but this came up when someone was attempting to show an action is deprecated in an OEM resource. For example, the desire was to have an actions property like this:
```
{
"Actions": {
"#ContosoManager.SuperCoolAction": {
"target": "/redfish/v1/Oem/Contoso/Manager/Actions/ContosoManager.SuperCoolAction"
},
"#ContosoManager.SuperCoolAction@Redfish.Deprecated": "This action has been deprecated for newer actions"
}
}
```
Using `@Redfish.Deprecated` inside of the Actions object wasn't being handled, as it was expecting everything to be an object.

Made change to allow for action names to be annotated

---

redfish_service_validator/catalog.py
redfish_service_validator/validateResource.py

Fix #560 
I originally considered using a simple "if current type == base type" to be the check, but that would help if the base type loop is larger. So, I opted to use a max loop count to cover more complicated schema definition loop conditions.

Added breakout condition when tracing a definition's type tree to prevent hangs due to invalid schemas with type loops

---

redfish_service_validator/tohtml.py
redfish_service_validator/validateResource.py

Added FAILS and WARNINGS values to results.
WARNING is sum of:
- "warningPresent" result
- "WARN" result of property
- "INVALID" result of property
- "Deprecated" result of property
FAILS is sum of:
- "exceptionResource" result
- "failMandatoryExist" result
- "failGet" result
- "FAIL" result of property
Signed-off-by: Zbigniew Jedliński zbigniew.jedlinski@non.se.com

Added the sum of fails and warnings

---

redfish_service_validator/catalog.py
redfish_service_validator/helper.py

Python 3.12 introduced a SyntaxWarning for invalid escape sequences in string literals. Use raw string literals where strings with backslash characters are required.

Fix syntax warnings with Python 3.12

---

redfish_service_validator/catalog.py

Found an issue related to mapping objects to schema definitions. This comes up in particular when an OEM extension is not providing `@odata.type`. The tool tries to dynamically map a definition and keep stepping into properties, but hits a point where it will break down on leaf properties. The change adds a missing return statement when it finds the property is not an object; not returning there guarantees an exception when it tries to pull out its `@odata.type` property.
Long term it might be worth rechecking this flow to not even attempt to map it in the first place, but that might take more time than its worth at the moment.

Break out of object schema mapping if not an object

---

redfish_service_validator/config.py

Issue was reported on the interop validator, but the same issue is present here too.

Hide password and token parameters from console output when running the tool from a config file

---

redfish_service_validator/validateRedfish.py

Found a gap in testing where if a linked resource is of the incorrect data type (like if AccountService in /redfish/v1/ points to a SessionService resource).

Fixed link verification to ensure the linked resource is of the expected data type

---

README.md
redfish_service_validator/RedfishServiceValidator.py
redfish_service_validator/config.py
redfish_service_validator/traverse.py

This PR introduces configurable parameters for HTTP request timeout (--requesttimeout) and retry attempts (--requestattempts).
The current static values for request timeouts and retries may not fit all environments, especially where network reliability or response times vary. I encountered this need during my usage of the tool and implemented this solution to improve usability.
**Changes**
1. Added `--requesttimeout` parameter to set the timeout in seconds for HTTP requests.
2. Added `--requestattempts` parameter to set the number of retry attempts after failed HTTP requests.
3. Updated `convert_config_to_args` func to convert these parameters to integer.
4. Updated the documentation to include descriptions of the new parameters.
Also addressed to #577 
Fix #577

Added requesttimeout and requestattempts arguments

---

redfish_service_validator/catalog.py

Upon visual inspection of some services, I noticed instances where date-time properties were not following ISO8601's format (such as missing a leading zero in the month). I found that the regex pattern we're using today allows for any format prior to the offset portion of the date-time value.

Corrected regex pattern for date-time properties

---

redfish_service_validator/catalog.py

- ActionInfo links in HTML logs are currently missing because:
- getLinks (catalog.py:1114) assigns the same Name ('ActionInfo') to each ActionInfo link
- Subsequent links overwrite previous ones, sharing the same uriName
- validateURITree returns only the last link
- Fixed by:
- Enumerating the generator (catalog.py:1111) to get a unique index (num)
- Adding the index to the 'ActionInfo' string to form each unique link name

fix: show all ActionInfo entries in HTML logs
