RedfishServiceValidator.py
expanded tabs to spaces, to avoid issues with other branch
=> whitespace only change

.travis.yml, README.md, RedfishServiceValidator.py, config.ini, requirements.txt, tests.py
A refactored version of the original Redfish Service Validator, which needs review over its outputs and the structure of the program and files before considering a pull.
[bladedlogs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/977534/bladedlogs.zip)
=> Refactoring of Redfish Service Validator

RedfishServiceValidator.py, config.ini, traverseService.py
Separated traversal and validation code into two separate py files.
Additionally, added the ability to specify a configuration file.  Other config options now include xml names, timeout for get and Service Mode, disallowing outgoing URLs
=> More Enhancements, including config options

AUTHORS.md, RedfishServiceValidator.py, tests.py, traverseService.py
Migrated majority of traversal code and resource initialization to independent file, with updated object to pass to functions.
Includes fixes for ServiceMode, Action Requirements, type inheritance.
Fixes #37-32
=> Testability modifications and corrections to type inheritance/actions

RedfishServiceValidator.py, config.ini, traverseService.py
Improvements synonymous with InteropValidator
Coinciding with postponing the pull request 06-22, added fix to additional properties, schema error with AutoExpand and a bad regex for Collections.
Included are a set of logs with 4 of the mockups provided on spmf
[logs_pr.zip](https://github.com/DMTF/Redfish-Service-Validator/files/1113442/logs_pr.zip)
=> Added cache improvement, additional prop check

RedfishServiceValidator.py, traverseService.py
Fixes #47, #48
Further log changes + accuracy, bugfix to Actions and added Response Time.
Log changes mostly include removing unneeded tags, adding response time, and removing Errors in getting metadata where they were not technically errors.
Accuracy changes fix missing annotations in public-bladed-partitions and bugfix to Actions.
=> Continuation of enhancements-06-22

RedfishServiceValidator.py, traverseService.py
Fixes issue #51 #52 
as well as:
ActionFail now properly not reported when target is missing
Additional printouts for missing metadata references (first pass), failed props
=> Refs now compounded $metadata first, logging and additionalprop fixes

README.md, RedfishServiceValidator.py, config.ini, rfSession.py, traverseService.py
Additional commit info includes suppressing certificate warnings on nochkcert, and common headers such as OData-Version
=> Added Session login, version checking, common headers

RedfishServiceValidator.py, config.ini, rfSession.py, traverseService.py
Corrected some nonsensical errors based on None
Changed ref acquirement from Context to Type, added regex for all Context formats
Do NOT accept HTML, only XML and Json via request
Added Certificate Bundle and proxy support, along with validating individual files/URIs
=> 8-08 enhancements

README.md, RedfishServiceValidator.py, config.ini, requirements.txt, traverseService.py
Removed requirement for bs4 version 4.5.3, added requirement for lxml.
Changed config options for easier printout, and added ability to add a Cache or validate Single File/URI.
Added support for Bios Attributes' "DynamicProperty".
Changed HTML and printouts for easier readability, more robust exception catches (in progress)
=> 8-14 Usability PR

README.md, RedfishServiceValidator.py, traverseService.py
Bugfix to previous mistaken capitalization error that would overlook certain tags.
Added statement to warn previous users to upgrade bs4 if possible, along with other minor changes.
=> Quick Fix to overlooked Complex properties

README.md, RedfishServiceValidator.py, requirements.txt, traverseService.py
Fixed print exception #102 and README + terminology changes (Compliance -> Conformance)
=> 09-27 enhancements

traverseService.py
=> Fix 101: Add Bearer Token Auth support

RedfishServiceValidator.py, config.ini, traverseService.py
Moved certain logic around to make config reading easier to modify when adding new options and features.
This also adds some missing features to the outside PR request "Fix101" which added Bearer Tokens.
=> Moved configParser from traverseService to RSV py, bugfix to fix 101

README.md, RedfishServiceValidator.py, config.ini, traverseService.py
Fixes #98
Does not add sampling as described in a later issue.
=> Added ability to limit entries from collections, LogEntry default 20

traverseService.py
Added logic to allow Registry resources to not have an @odata.context property. Code now does its best to construct a context in that case. Also fixed a couple of other corner case errors that I saw during testing.
Fixes #126
=> @odata.context not required for Registry resources

traverseService.py
Added validation that @odata.id exists in resources. But allows @odata.id to be missing in Registry resources.
If an @odata.id is missing from a "regular" resource, an error like this is emitted:
```
ERROR - /redfish/v1/Systems/System.Embedded.1/Bios: Json does not contain @odata.id
```
But validation continues for that resource so that other issues can be reported.
If an @odata.id is missing from a Registry resource, a debug message like this is emitted:
```
DEBUG - /redfish/v1/Registries/BaseMessages/BaseRegistry.v1_0_0.json: @odata.id missing, but not required for Registry resource
```
Fixes #131
=> Add check for @odata.id in resources

traverseService.py
Allow a user to specify extra headers needed for their implementation in the config file.
=> Allow extra headers

traverseService.py
Updated check for specified ca_bundle to allow it to be a file or a directory.
=> ca_bundle can be a file or directory

README.md, SelfSignedCerts.md
Incorporated my notes from issue #69 into a new SelfSignedCerts.md file.
Fixes #69
=> Add SelfSignedCerts.md with CA_BUNDLE creation walkthrough

RedfishServiceValidator.py
Includes these fixes:
- fix display of null values
- fix display of types from Registries
- add validation of primitive types in checkPropertyConformance()
Fixes #145 
Fixes #147
=> HTML report improvements for issue 137, part 2

traverseService.py
Avoid runtime exception and add error message when $metadata Reference has Include for wrong Namespace.
Fixes #148
=> Better error handling for issue 148

RedfishServiceValidator.py
=> Added log changes for Referenceable Members

RedfishServiceValidator.py
If a deprecated property was detected, the tool generated an error rather than a warning.
The code was updated to generate a warning in this case instead. And also to show the property is deprecated in the report by putting 'Deprecated' in the Result column with a yellow background. A 'warnDeprecated' counter is now included in the summery header for each resource that has any deprecated properties. A 'failSchema' counter is no longer indicated for deprecated properties.
Fixes #178 
Report BEFORE:
Report AFTER:
=> Change deprecated property issue from error to warning

RedfishServiceValidator.py
Updated the Actions validation to allow (but not require) the "title" property.
Fixes #209
=> Property "title" is allowed in Actions

traverseService.py
Fixed issue with getSchemaDetails() / getSchemaDetailsLocal() when the $metadata could not be retrieved from the service and has to be retrieved via the local cache.
For example, getSchemaDetails() gets called like this: 
`getSchemaDetails(SchemaType='#ServiceRoot.v1_3_0.ServiceRoot', SchemaURI='/redfish/v1/$metadata#ServiceRoot.ServiceRoot')`
And if the $metadata could not be retrieved from the service, the fallback is to get it locally. When the local call is made, the frag at the end of the SchemaURI is lost on the call to getSchemaDetailsLocal(). So it gets called like this:
`getSchemaDetailsLocal(SchemaType='#ServiceRoot.v1_3_0.ServiceRoot', SchemaURI='/redfish/v1/$metadata')`
when it should be:
`getSchemaDetailsLocal(SchemaType='#ServiceRoot.v1_3_0.ServiceRoot', …
=> Correct problem with reading $metadata from local cache

traverseService.py
Fix for https://github.com/DMTF/Redfish-Service-Validator/issues/227
=> Updated traverseService.py to clean up bad log formatting.

RedfishServiceValidator.py, metadata.py, traverseService.py
Corrected a few minor mistakes created or noted between last PR and now
Corrected annotations being incorrectly treated as unknown.
Corrected additional block being triggered improperly (should probably just throw a warning in most cases), and oem links being followed with OemCheck set to Off
=> Fixed annotation/metadata errors, custom arglist, log init lines

rfSession.py
=> fixed logger.info statment for Session Authentication

RedfishServiceValidator.py, rfSchema.py, traverseService.py
Repairs crash with OemCheck using wrong variable
Add option to support Uri Checking via annotation
Added an extra version print and cache bugfix
=> Adds OEM Check fix and URI Check option

RedfishServiceValidator.py, rfSchema.py, traverseService.py
Perform stricter full string matches rather that partial matches.
=> Small fix to regex matching

RedfishServiceValidator.py, rfSchema.py, tohtml.py, traverseService.py
Display JSON and Return Code in HTML log, hideable config
Added Id error, Test Summary block
[Conformance Test Summary.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2540006/Conformance.Test.Summary.zip)
=> Extra HTML Features

RedfishServiceValidator.py, traverseService.py
=> Properly skip Links, getAllLinks cleanup, warn on link slash

RedfishServiceValidator.py, metadata.py, rfSchema.py, simpletypes.py, tests/complexeval.py, tests/simpleeval.py, traverseService.py
Includes changes to support 
PropertyType Edm.Duration, include test changes
Annotation Revision
Updated schema pack to 2018.3
Debug logging only on command line
ONLY replace expected resource with service resource if service resource is accessible, which allows for SingleFile payload mode to function.
edit:
example
```
WARNING - FanName: The given property is deprecated by revision This property has been Deprecated in favor of the property Name.
```
=> Updated to changes for 2018.3

RedfishServiceValidator.py, traverseService.py
commits held over from branch `reflink_fix`
=> Small fix for Registry Context + Reference Link fix

RedfishServiceValidator.py, traverseService.py
Fixes #196
Fixes #313 
Adds check if current payload is a file
=> Fixed issue with HttpHeaders null collection

traverseService.py
=> Downgrade Warn to Debug on missing odata.type

traverseService.py
Allows Registry check on resource itself, not its parent
=> Fix to parental check on Registries

RedfishServiceValidator.py
No longer treats OriginOfCondition as required resolvable link.
Fixes #333
=> Fix to detecting OriginOfCondition not existing after processing

traverseService.py
Removes operation of trailing slash during URL resolution.
=> Fix link allocation for null objects in collection of Complex objects

rfSchema.py, traverseService.py
Adds parameter `topVersion` and a few lines to accommodate information to describe the documents highest possible version.
=> Add checks to OEM/Dynamic property version limits

RedfishServiceValidator.py, rfSchema.py, traverseService.py
Fixes some missing config function and solution to HighestVersion bug
=> Fixes to some plugfest bugs and invalid version issue

README.md, RedfishServiceValidator.py, common/schema.py, test_conf.json, tests/complexeval.py, tohtml.py, traverseService.py, validateResource.py, validateSpecial.py
Add distinguishing tests for Excerpt copy properties.
TODO:  Review if the conditions are satisfactory for ExcerptCopy properties.
TODO:  PR #405
=> Add support for Excerpt Copy

traverseService.py
Correct oversight of rewriting rfSession as session.
Fix #408
=> Update traverseService.py rfSession include

common/schema.py
=> Add missing import lost from PR

common/metadata.py
=> Remove erroneous check for Resource_v1 in metadata

CHANGELOG.md, CONTRIBUTING.md, RedfishServiceValidator.py
=> 2.0.4 Versioning

common/catalog.py, validateRedfish.py
Fix #429 
Added proper checking for usage of null for object as both singletons and arrays based upon the "Nullable=false" term.
=> Added handling for null objects

CHANGELOG.md, RedfishServiceValidator.py
=> 2.0.8 Versioning

common/traverse.py
=> fix #443 to avoid waiting when requests does not return

CHANGELOG.md, RedfishServiceValidator.py
=> 2.0.9 Versioning

CHANGELOG.md, RedfishServiceValidator.py
=> 2.1.0 Versioning

CHANGELOG.md, RedfishServiceValidator.py
=> 2.1.1 Versioning

README.md, RedfishServiceValidator.py, RedfishServiceValidatorGui.py, common/config.py, common/traverse.py, requirements.txt, validateRedfish.py, validateResource.py
Note: requires a fix to the python-redfish-library (version 3.1.2 or higher)
=> Added 'mockup' option to be able to override resources based on a mockup directory

common/helper.py
`info` is a dict here, but it call `append` would cause a crash. Please help to review if the logic is correct here. Thanks!
=> Fix the wrong use of 'append' for dict

validateRedfish.py
=> Corrected checking for required properties that are objects

CHANGELOG.md, RedfishServiceValidator.py
=> 2.1.2 Versioning

common/catalog.py, validateResource.py
Minor enhancements (no logic changes)
=> Enhance code quality (Pythonic)

RedfishServiceValidator.py, common/config.py
* Disable interpolation for configparser to allow '%' value
Signed-off-by: Jordan Chen <jordanchen@google.com>
=> Support unixsocket

validateRedfish.py
=> Skip deprecated property check for required properties

common/traverse.py
Issue found where the catalog does not pick up schema files on the service, but not yet cached, which can introduce errors.
Fix #466
=> Corrected ordering for building the data model to be performed after scanning $metadata

CHANGELOG.md, RedfishServiceValidator.py
=> 2.1.3 Versioning

CHANGELOG.md, RedfishServiceValidator.py
=> 2.1.4 Versioning

README.md, RedfishServiceValidator.py, RedfishServiceValidatorGui.py, common/catalog.py, common/config.py, common/traverse.py, requirements.txt, schema_pack.py, validateRedfish.py
Fix #483 
Fix #484 
Fix #467 
Added check to ensure array properties are returned as arrays before iterating over its values
Added context-driven pattern checking for 'DurableName'
Added proxy arguments for controlling proxy usage with external sites and the service
=> Minor enhancements

RedfishServiceValidator.py, common/catalog.py, schema_pack.py, validateRedfish.py, validateResource.py
* Fix arguments not converted during string formatting
* Refine the usage of custom debug level for logger
* Add default value for optional parameters
=> Some refinements

README.md, RedfishServiceValidatorGui.py
Fix #503
Also did a general cleanup of the readme.
=> Scroll bars for GUI config window

common/traverse.py, requirements.txt
Tool incorrectly appends target host to external schema definitions, causing errors in resolution.
Signed-off-by: Tomas <tomas.g.2012@gmail.com>
=> Corrected out-of-service requests for xml files

redfish_service_validator/validateRedfish.py
=> Fixes access to None object in validateEntity

redfish_service_validator/catalog.py, redfish_service_validator/validateResource.py, tests/test_catalog.py, tests/testdata/schemas/Example_v1.xml
Fixes #531
Fixes #533
Logic now only checks the last Id in the chain if it matches the current Resource.
=> Simplify URI checking for Ids

redfish_service_validator/catalog.py, redfish_service_validator/validateResource.py
=> Added back flags to ignore URI checking for resources referenced by payload annotations

redfish_service_validator/validateRedfish.py
This is a suggestion to write the version information in case of a "Deprecated" result into the generated files and to make it usable for an automated processing of the csv files.
If the version is available, it is reported as "Result" in the format "Deprecated/v1_2_3", instead of "Deprecated" only .
When analyzing the csv files, this version can be compared with the reported resource version - and depending on the use case, this helps to decide if the "Deprecated" should be treated as an error, as a warning, or even as normal behavior.
Issue #545
=> Add version information to result "Deprecated"

redfish_service_validator/tohtml.py, redfish_service_validator/validateRedfish.py
Prevents overriding the error entry in messages
Added log entry for actions with bad names.
Fixes #513
=> Fix to Action validation overriding variable name, added log entry

redfish_service_validator/catalog.py
Fixes #529 
Tweaked version code to accurately check highest type from the Parent (where applicable), and not based on the type itself.
=> Fixes to highest version checks without an odata.type defined

RedfishServiceValidator.py, redfish_service_validator/RedfishServiceValidator.py, redfish_service_validator/RedfishServiceValidatorGui.py
=> Add a wrapper function to the main entrypoint

README.md, redfish_service_validator/catalog.py, redfish_service_validator/validateResource.py
=> Added exception handling when traversing links if the schema definition for the link is invalid

redfish_service_validator/RedfishServiceValidator.py, redfish_service_validator/catalog.py, redfish_service_validator/validateRedfish.py, redfish_service_validator/validateResource.py
Changes to ensure OEM links are allocated and skipped, along with Actions being verified.
Some minor variable name changes for clarity included.
[logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/14541317/logs.zip)
edit:  Including live system logs, warning as extracted files are over 100mb
[logs_live_system.zip](https://github.com/DMTF/Redfish-Service-Validator/files/14541442/logs_live_system.zip)
Fix #553 
Fix #440
=> Validator OEM Check link fix and OEM Action fix

redfish_service_validator/validateRedfish.py
=> Reduced severity of missing schema for an action from error to warning to be consistent with other warnings

redfish_service_validator/validateRedfish.py
Ensures that write-only properties return a null
=> Added write only check for permissions such as password

redfish_service_validator/validateRedfish.py
Redfish Spec 1.16.0 added "@Redfish.AllowablePattern" and "@Redfish.AllowableNumbers" annotations for properties and action parameters.
=> Updated action testing to allow for new annotations for action parameters

redfish_service_validator/RedfishServiceValidator.py, redfish_service_validator/traverse.py, redfish_service_validator/validateRedfish.py
=> Changes to cache hit to use URIs without fragments

redfish_service_validator/catalog.py
RSV currently checks for missing @Redfish.ActionInfo only in standard actions. This fix adds the same check for OEM actions. I added a helper function to return a generator with all action dictionaries.
=> Fix missing ActionInfo check for OEM actions in RSV

RedfishServiceValidator.py, redfish_service_validator/RedfishServiceValidator.py, redfish_service_validator/catalog.py, redfish_service_validator/config.py, redfish_service_validator/helper.py, redfish_service_validator/logger.py, redfish_service_validator/metadata.py, redfish_service_validator/schema_pack.py, redfish_service_validator/tohtml.py, redfish_service_validator/traverse.py, redfish_service_validator/validateRedfish.py, redfish_service_validator/validateResource.py, tests/test_catalog.py
Consolidated logging configuration to `logger.py` and removed Counter objects across program, as logging operations now contain an id and error level referring to the type of message.
HTML Log changes for easier readability for non-technical users, changes to align with current Protocol Validator HTML log summary.  Slimmed down several elements.
General code formatting changes and variable name clarity.
Sample Logs:
[logs.zip](https://github.com/user-attachments/files/20301605/logs.zip)
TODO:
- Review the details between the new log and original to maintain level of detail necessary to diagnose issues.
=> Updates to Log output and associated functions
